Show the default toolchain when there is no override

diff --git a/src/multirustproxy b/src/multirustproxy
--- a/src/multirustproxy
+++ b/src/multirustproxy
@@ -122,7 +122,11 @@ fi
 toolchain="${MULTIRUST_TOOLCHAIN-}"
 if [ -z "$toolchain" ]; then
     toolchain="$(call_multirust ctl override-toolchain)"
-    need_ok '`multirust ctl override-toolchain` failed'
+    if [ $? != 0 ]; then
+	# If this fails, multirust will display an error,
+	# which looks better than multirustproxy doing so.
+	return 1
+    fi
     assert_nz "$toolchain" "toolchain is empty"
 fi
 
